---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adamcoro/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R gws101-assignment2 $DEPLOYPATH